# Generated by Django 5.1.2 on 2024-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_latitude_branch_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycompanylink',
            old_name='original_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='original_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='deliverycompanylink',
            name='short_link',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website_short_link',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='short_link',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='icon',
            field=models.ImageField(default='images/about_us/default_about_us.png', upload_to='media/images/about_us/'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='file',
            field=models.FileField(upload_to='media/images/catalogs/'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='icon',
            field=models.ImageField(default='media/images/delivery_company/default_company.png', upload_to='media/images/delivery_company/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='media/images/image_galleries/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='media/images/organizations/logos/default.png', upload_to='media/organizations/logos/'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='reelsgallery',
            name='video',
            field=models.FileField(upload_to='media/images/reels_galleries/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(default='media/images/social_media/default_media.png', upload_to='media/images/social_media/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.ImageField(upload_to='media/images/templates/'),
        ),
    ]
