# Generated by Django 5.1.2 on 2024-12-20 08:40

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_catalogurl_organizationinfolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='short_url',
            field=models.URLField(blank=True, default=utils.helper.generateShortUrl, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='CatalogUrl',
        ),
    ]
