# Generated by Django 5.1.2 on 2024-12-20 09:19

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_catalog_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='short_url',
            field=models.SlugField(default=utils.helper.generateShortUrl, max_length=300),
        ),
    ]
