# Generated by Django 5.1.2 on 2024-12-20 10:07

import django.db.models.deletion
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_catalog_short_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationInfoLink',
            new_name='OrganizationInfoUrl',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='social_media',
        ),
        migrations.CreateModel(
            name='DeliveryCompanyUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('short_url', models.SlugField(default=utils.helper.generateShortUrl)),
                ('active', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.deliverycompany')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('short_url', models.SlugField(default=utils.helper.generateShortUrl)),
                ('active', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.socialmedia')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryCompanyLink',
        ),
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
