# Generated by Django 5.1.2 on 2024-12-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_organizationinfolink_organizationinfourl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycompanyurl',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
