# Generated by Django 5.1.2 on 2024-12-20 15:49

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_deliverycompanyurl_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='long',
        ),
        migrations.AddField(
            model_name='organization',
            name='card_url',
            field=models.SlugField(default=utils.helper.generateShortUrl),
        ),
        migrations.AddField(
            model_name='organization',
            name='website_short_url',
            field=models.SlugField(default=utils.helper.generateShortUrl),
        ),
        migrations.AlterField(
            model_name='organization',
            name='commercial_register_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
