# Generated by Django 5.1.2 on 2024-12-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_createat_organization_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='card_url',
            new_name='qr_url',
        ),
    ]
