# Generated by Django 5.1.2 on 2024-12-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_card_url_organization_qr_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='qr_url',
            new_name='card_url',
        ),
    ]
