# Generated by Django 5.1.2 on 2024-12-19 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='media/images/users/placeholder.jpg', upload_to='media/images/users/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be between 7 and 20 digits.', regex='^\\d{7,20}$')], verbose_name='الهاتف'),
        ),
    ]
